# PermissionsPlugin
# Плагин на пермишены, использующийся вами (оставьте пустым, если хотите отключить интеграцию)
# Доступные на данный момент плагины: LuckPerms, Vault (включает в себя поддержку множества плагинов, список: https://www.spigotmc.org/resources/vault.34315/)
# ------------------------------------------------------------------
# CheckForUpdates
# Проверка на наличие не установленных обновлений плагина
# ------------------------------------------------------------------
# BotToken
# Токен, необходимый для работы бота. Получить его можно здесь: https://discord.com/developers/applications
# ------------------------------------------------------------------
# BotPrefix
# Префикс, использующийся в командах бота
# ------------------------------------------------------------------
# Activity
# Type - тип активности бота (доступные: default, streaming, listening, watching, custom_status, competing)
# Text - текст активности
# ------------------------------------------------------------------
# GroupRoles
# Сюда вводим роли по следующему формату: id_роли: 'название_группы'
# Пример: 905508941230915684: 'admin'
# Данные роли будут автоматически выдаваться, если у игрока есть соответствующая группа
# ------------------------------------------------------------------
# AdminRoles
# Сюда нужно вводить id ролей (списком). Эти роли смогут выполнять команды для администраторов.
# Пример: AdminRoles: [905508941230915684, 123123123131231233]
# ------------------------------------------------------------------
# VerifiedRole
# Id - id роли, выдающейся после верификации
# Enabled - true - выдавать, false - не выдавать
# ------------------------------------------------------------------
# 2FAType
# Тип двухфакторной аутентификации. code - ввести код, reaction - нажать на реакцию в Discord'e
# ------------------------------------------------------------------
# 2FASessions
# Включить ли сессии (ненадобность прохождения 2FA, если айпи сохранился) для двухфакторной аутентификации
# ------------------------------------------------------------------
# Default2FAValue
# Включать ли двухфакторную аутентификацию игроку сразу после верификации
# ------------------------------------------------------------------
# ForceVerification
# Обязывать ли игроков пройти верификацию
# ------------------------------------------------------------------
# DelayedRolesCheck
# Включить ли проверку ролей каждые Delay секунд (если выключить, то будет проверять только при выходе и входе игрока на сервер)
# Enabled - true - включить, false - выключить
# Delay - задержка между проверками
# ------------------------------------------------------------------
# DelayedNamesCheck
# Включить ли проверку никнеймов каждые Delay секунд (если выключить, то будет проверять только при выходе и входе игрока на сервер)
# Enabled - true - включить, false - выключить
# Delay - задержка между проверками
# ------------------------------------------------------------------
# GuildVoiceRewards
# Включить ли выдачу наград за проведение времени (Time) в войсах на сервере в Discord
# Enabled - true - включить, false - выключить
# Time - минимальное время для получения награды
# Reward - команда, выдающаяся при достижении минимального времени (выполняется несколько раз, если минимальное время отыграно несколько раз)
# BlacklistedChannels - ID игнорирующихся каналов. Пример: BlacklistedChannels: [905508941230915684, 123123123131231233]
# ------------------------------------------------------------------
# MessagesChannel
# Включить ли отправку сообщений из игры в Discord (/du sendtodiscord)
# Enabled - true - включить, false - выключить
# Id - ID канала, в который будут отправляться сообщения
# ------------------------------------------------------------------
# Database
# Использование базы данных для хранения данных плагина (вместо data.yml)
# Type - тип базы данных (доступные: mysql) (чтобы отключить - оставьте пустую строку, в этом случае все будет работать по data.yml)
# Host - хост (стандартный - localhost)
# Port - порт (стандартный - 3306)
# Database - название использующейся плагином базы данных
# Username - имя пользователя (стандартное - root)
# Password - пароль (по стандарту его нет)

PermissionsPlugin: 'LuckPerms'
CheckForUpdates: true
Discord:
  BotToken: ''
  BotPrefix: '!'
  Activity:
    Type: 'default'
    Text: 'Minecraft'
  GroupRoles: {}
  AdminRoles: []
  VerifiedRole:
    Id: -1
    Enabled: true
  2FAType: 'reaction'
  2FASessions: true
  Default2FAValue: false
  ForceVerification: false
  DelayedRolesCheck:
    Enabled: true
    Delay: 30
  DelayedNamesCheck:
    Enabled: true
    Delay: 30
  GuildVoiceRewards:
    Enabled: false
    Time: 600
    Reward: 'eco give %player% 100'
    BlacklistedChannels: []
  MessagesChannel:
    Enabled: true
    Id: -1
Database:
  Type: ''
  Host: 'localhost'
  Port: 3306
  Database: 'DiscordUtils'
  Username: 'root'
  Password: ''