# PermissionsPlugin
# Плагин на пермишены, использующийся вами (оставьте пустым, если хотите отключить интеграцию)
# Доступные на данный момент плагины: LuckPerms, Vault (включает в себя поддержку множества плагинов, список: https://www.spigotmc.org/resources/vault.34315/)
# ------------------------------------------------------------------
# CheckForUpdates
# Проверка на наличие не установленных обновлений плагина
# ------------------------------------------------------------------
# BotToken
# Токен, необходимый для работы бота. Получить его можно здесь: https://discord.com/developers/applications
# ------------------------------------------------------------------
# BotPrefix
# Префикс, использующийся в командах бота
# ------------------------------------------------------------------
# BotCommandTextChannels
# Текстовые каналы, в которых бот реагирует на команды (если список пуст, то бот реагирует на команды во всех текстовых каналах)
# ------------------------------------------------------------------
# AsyncBotLoading
# Включить ли асинхронную загрузку бота (желательно включить, если она у вас по каким-то причинам не работает, то выключите)
# ------------------------------------------------------------------
# Activities
# Enabled - true - включено, false - выключено
# UpdateDelay - время в секундах, циклично по истечению которого будет обновляться активность бота
# Type - тип активности бота (доступные: default, streaming, listening, watching, competing)
# Text - текст активности
# ------------------------------------------------------------------
# SuccessfulEmbedColor
# Цвет embed-сообщений для сообщений типа successful
# ------------------------------------------------------------------
# InformationEmbedColor
# Цвет embed-сообщений для сообщений типа information
# ------------------------------------------------------------------
# ErrorEmbedColor
# Цвет embed-сообщений для сообщений типа error
# ------------------------------------------------------------------
# GroupRoles
# Данные роли будут автоматически выдаваться, если у игрока есть соответствующая группа
# Сюда вводим роли по следующему формату: id_роли: 'название_группы'
# Пример:
# GroupRoles:
#   905508941230915684: 'admin'
#   934834130198751892: 'vip'
# ------------------------------------------------------------------
# AdminRoles
# Сюда нужно вводить id ролей (списком). Эти роли смогут выполнять команды для администраторов.
# Пример: AdminRoles: [905508941230915684, 123123123131231233]
# ------------------------------------------------------------------
# VerifiedRole
# Enabled - true - выдавать, false - не выдавать
# Id - id роли, выдающейся после верификации
# ------------------------------------------------------------------
# 2FAType
# Тип двухфакторной аутентификации. code - ввести код, reaction - нажать на реакцию в Discord'e
# ------------------------------------------------------------------
# 2FASessions
# Включить ли сессии (ненадобность прохождения 2FA, если айпи сохранился) для двухфакторной аутентификации
# ------------------------------------------------------------------
# 2FASessionTime
# Время, в течение которого действительна сессия 2FA (указывается в секундах) (если меньше, либо равно 0, то действует до рестарта плагина)
# ------------------------------------------------------------------
# Default2FAValue
# Включать ли двухфакторную аутентификацию игроку сразу после верификации
# ------------------------------------------------------------------
# NotifyAboutDisabled2FA
# Отправлять ли игроку при каждом заходе на сервер сообщение о том, что у него выключена двухфакторная аутентикация (если выключена)
# ------------------------------------------------------------------
# ForceVerification
# Обязывать ли игроков пройти верификацию
# ------------------------------------------------------------------
# AllowedCommandsBeforePassing2FA
# Список разрешенных команд перед прохождением 2FA
# ------------------------------------------------------------------
# ActionsAfterFailing2FA
# Список действий, выполняющихся при провале 2FA n раз
# Messages - сообщения, отправляющиеся при провале 2FA n раз
# Commands - команды, выполняющиеся при провале 2FA n раз
# ------------------------------------------------------------------
# CommandsAfterVerification
# Команды, которые выполняются сразу после того, как игрок верифицирует свой аккаунт (%player% - плейсхолдер для получения ника игрока)
# ------------------------------------------------------------------
# CommandsAfterServerBoosting
# Команды, которые выполняются сразу после того, как игрок бустит сервер в Discord (%player% - плейсхолдер для получения ника игрока, %user% - плейсхолдер для получения ник игрока в Discord)
# ------------------------------------------------------------------
# DelayedRolesCheck
# Включить ли проверку ролей каждые Delay секунд (если выключить, то будет проверять только при выходе и входе игрока на сервер)
# Enabled - true - включить, false - выключить
# Delay - задержка между проверками
# ------------------------------------------------------------------
# DelayedNamesCheck
# Включить ли проверку никнеймов каждые Delay секунд (если выключить, то будет проверять только при выходе и входе игрока на сервер)
# Enabled - true - включить, false - выключить
# Delay - задержка между проверками
# ------------------------------------------------------------------
# GuildVoiceRewards
# Включить ли выдачу наград за проведение времени (Time) в войсах на сервере в Discord
# Enabled - true - включить, false - выключить
# Time - минимальное время для получения награды
# Reward - команда, выдающаяся при достижении минимального времени (выполняется несколько раз, если минимальное время отыграно несколько раз)
# BlacklistedChannels - ID игнорирующихся каналов. Пример: BlacklistedChannels: [905508941230915684, 123123123131231233]
# ------------------------------------------------------------------
# MessagesChannel
# Включить ли отправку сообщений из игры в Discord (/du sendtodiscord)
# Enabled - true - включить, false - выключить
# Id - ID канала, в который будут отправляться сообщения
# ------------------------------------------------------------------
# Database
# Использование базы данных для хранения данных плагина (вместо data.yml)
# Type - тип базы данных (доступные: mysql) (чтобы отключить - оставьте пустую строку, в этом случае все будет работать по data.yml)
# Host - хост (стандартный - localhost)
# Port - порт (стандартный - 3306)
# Database - название использующейся плагином базы данных
# Username - имя пользователя (стандартное - root)
# Password - пароль (по стандарту его нет)

PermissionsPlugin: 'LuckPerms'
CheckForUpdates: true
Discord:
  BotToken: ''
  BotPrefix: '!'
  BotCommandTextChannels: []
  AsyncBotLoading: true
  Activities:
    Enabled: true
    UpdateDelay: 10
    1:
      Type: 'default'
      Text: 'Minecraft'
    2:
      Type: 'watching'
      Text: 'mirrerror#4790'
    3:
      Type: 'watching'
      Text: 'DiscordUtils'
  SuccessfulEmbedColor: '#0AAC00'
  InformationEmbedColor: '#ECC846'
  ErrorEmbedColor: '#A80000'
  GroupRoles: {}
  AdminRoles: []
  VerifiedRole:
    Enabled: false
    Id: -1
  2FAType: 'reaction'
  2FASessions: true
  2FASessionTime: 900
  Default2FAValue: false
  NotifyAboutDisabled2FA: true
  ForceVerification: false
  AllowedCommandsBeforePassing2FA: []
  ActionsAfterFailing2FA:
    1:
      Messages:
        - 'Вы провалили двухфакторную аутентификацию &bодин&f раз. Если Вы провалите ее еще два раза, то Ваш IP-адрес будет заблокирован. '
      Commands: []
    3:
      Messages: []
      Commands:
        - 'banip %player% 30m Подозрительная активность.'
  CommandsAfterVerification: []
  CommandsAfterServerBoosting: []
  DelayedRolesCheck:
    Enabled: true
    Delay: 30
  DelayedNamesCheck:
    Enabled: true
    Delay: 30
  GuildVoiceRewards:
    Enabled: false
    Time: 600
    Reward: 'eco give %player% 100'
    BlacklistedChannels: []
  MessagesChannel:
    Enabled: false
    Id: -1
Database:
  Type: ''
  Host: 'localhost'
  Port: 3306
  Database: 'DiscordUtils'
  Username: 'root'
  Password: ''