# PermissionsPlugin
# Permission plugin that you are currently using (set it to '' if you want to disable the permission integration)
# Available plugins: LuckPerms, Vault (includes many plugins support: https://www.spigotmc.org/resources/vault.34315/)
# ------------------------------------------------------------------
# CheckForUpdates
# Set it to true if you want plugin to check for available updates, otherwise set it to false
# ------------------------------------------------------------------
# BotToken
# Token that is required for the bot to work. You can get it here: https://discord.com/developers/applications
# ------------------------------------------------------------------
# BotPrefix
# Prefix that is used in bot's commands
# ------------------------------------------------------------------
# BotCommandTextChannels
# Text channels, in which the bot handles the commands (if it is empty, the bot will handle the commands in all the text channels)
# ------------------------------------------------------------------
# AsyncBotLoading
# Enable or not the bot's async loading (I strongly recommend you to keep this setting enabled, but if it doesn't work for you for some reason, feel free to disable it)
# ------------------------------------------------------------------
# Activities
# Enabled - true - enabled, false - disabled
# UpdateDelay - time (in seconds), after which the bot activity will be updated (cyclically)
# Type - activity type (available: default, streaming, listening, watching, competing)
# Text - activity text
# ------------------------------------------------------------------
# SuccessfulEmbedColor
# Successful embed messages' type color
# ------------------------------------------------------------------
# InformationEmbedColor
# Info embed messages' type color
# ------------------------------------------------------------------
# ErrorEmbedColor
# Error embed messages' type color
# ------------------------------------------------------------------
# GroupRoles
# These roles will automatically be assigned if the player owns respective groups
# Format: role_id: 'group_name'
# For example:
# GroupRoles:
#   905508941230915684: 'admin'
#   934834130198751892: 'vip'
# ------------------------------------------------------------------
# AdminRoles
# Members with these roles are considered as administrators and will be able to perform admin commands (such as !sudo)
# For example: AdminRoles: [905508941230915684, 123123123131231233]
# ------------------------------------------------------------------
# VerifiedRole
# Enabled - true - assign, false - don't assign
# Id - role id that is assigned after the verification
# ------------------------------------------------------------------
# 2FAType
# Type of the 2FA. Available: code - enter the code, reaction - click on a reaction in Discord
# ------------------------------------------------------------------
# 2FASessions
# Whether to enable or not 2FA sessions (uselessness of passing 2FA if the player's IP address is the same)
# ------------------------------------------------------------------
# 2FASessionTime
# Time during which is valid 2FA session (in seconds) (if it is less or equal to 0, it will be valid till the plugin restart)
# ------------------------------------------------------------------
# 2FATimeToAuthorize
# Time during which the player has to pass 2FA, otherwise he will be kicked (in seconds) (if less or equal to 0, he will not be limited by time)
# ------------------------------------------------------------------
# Default2FAValue
# Whether to enable or not 2FA for the player when he verify his account
# ------------------------------------------------------------------
# NotifyAboutDisabled2FA
# Whether to send for the player or not information about disabled 2FA (if it is disabled)
# ------------------------------------------------------------------
# ForceVerification
# Whether to force players to verify their accounts or not
# ------------------------------------------------------------------
# AllowedCommandsBeforePassing2FA
# List of the allowed commands before passing 2FA
# ------------------------------------------------------------------
# ActionsAfterFailing2FA
# List of the actions that will be performed after the player fails 2FA n times
# Messages - messages that are sent when the player fails 2FA n times
# Commands - commands that are executed when the player fails 2FA n times
# ------------------------------------------------------------------
# CommandsAfterVerification
# Commands that are performed after the player verify his account (%player% - placeholder for the player nickname)
# ------------------------------------------------------------------
# CommandsAfterUnlink
# Commands that are performed after the player unlink his Discord account (%player% - placeholder for the player nickname)
# ------------------------------------------------------------------
# CommandsAfterServerBoosting
# Commands that are performed after the player boosts your Discord server (%player% - placeholder for the player nickname, %user% - placeholder for the player's Discord nickname)
# ------------------------------------------------------------------
# DelayedRolesCheck
# Whether to enable or disable the roles check every Delay seconds (if it is disable, the plugin will check it only when players join and leave the server)
# Enabled - true - enable, false - disable
# Delay - checks delay
# ------------------------------------------------------------------
# DelayedNamesCheck
# Whether to enable or disable the nicknames check every Delay seconds (if it is disable, the plugin will check it only when players join and leave the server)
# Enabled - true - enable, false - disable
# Delay - checks delay
# ------------------------------------------------------------------
# GuildVoiceRewards
# Whether to enable or not the reward giving for spending time in the voice channels on your server in Discord
# Enabled - true - enable, false - disable
# Time - minimum time for achieving the reward (in seconds)
# Reward - command that is executed if the player reach the minimum time (executes multiple times if the minimum time is played by player more than one time)
# BlacklistedChannels - ignored channel IDs. For example: BlacklistedChannels: [905508941230915684, 123123123131231233]
# ------------------------------------------------------------------
# MessagesChannel
# Whether to enable or not the possibility to send messages to Discord from the game (/du sendtodiscord)
# Enabled - true - enable, false - disable
# Id - text channel ID, in which will appear the messages
# ------------------------------------------------------------------
# ServerActivityLogging
# Whether to enable or not the logging of some server events to an Discord channel
# Enabled - true - enable, false - disable
# ChannelId - text channel ID, in which will appear the logging messages
# JoinEmbedColor - join embed messages' type color
# QuitEmbedColor - quit embed messages' type color
# DeathEmbedColor - death embed messages' type color
# ChatEmbedColor - chat embed messages' type color
# ------------------------------------------------------------------
# Console
# Whether to enable or not the virtual console in the specified Discord channel
# Enabled - true - enable, false - disable
# ChannelId - text channel ID, in which will appear the console messages
# BlacklistedCommands - commands that can't be executed from the virtual console
# ------------------------------------------------------------------
# NotifyAboutMentions
# Whether to notify the verified players about the mentions in Discord or not
# Enabled - true - enable, false - disable
# Title - title message settings
# Enabled - true - enable, false - disable
# FadeIn - fade in time
# Stay - stay time
# FadeOut - fade out time
# Title - title text (top)
# Subtitle - subtitle text (bottom)
# Message - chat message settings
# Enabled - true - enable, false - disable
# Text - message text
# Sound - sound settings
# Enabled - true - enable, false - disable
# Type - sound type
# Volume - sound volume
# Pitch - sound pitch
# ------------------------------------------------------------------
# Database
# Usage of the database instead of the data.yml file to save and load your data
# Type - database type (available: mysql) (set it to '' to disable this feature, in this case the data will be stored in the data.yml file)
# Host - database host (by default - localhost)
# Port - database port (by default - 3306)
# Database - database name
# Username - database username (by default - root)
# Password - database password (by default there is not a password)

PermissionsPlugin: 'LuckPerms'
CheckForUpdates: true
Discord:
  BotToken: ''
  BotPrefix: '!'
  BotCommandTextChannels: []
  AsyncBotLoading: true
  Activities:
    Enabled: true
    UpdateDelay: 10
    1:
      Type: 'default'
      Text: 'Minecraft'
    2:
      Type: 'watching'
      Text: 'mirrerror#7777'
    3:
      Type: 'watching'
      Text: 'DiscordUtils'
  SuccessfulEmbedColor: '#0AAC00'
  InformationEmbedColor: '#ECC846'
  ErrorEmbedColor: '#A80000'
  GroupRoles: {}
  AdminRoles: []
  VerifiedRole:
    Enabled: false
    Id: -1
  2FAType: 'reaction'
  2FASessions: true
  2FASessionTime: 900
  2FATimeToAuthorize: 30
  Default2FAValue: false
  NotifyAboutDisabled2FA: true
  ForceVerification: false
  AllowedCommandsBeforePassing2FA: []
  ActionsAfterFailing2FA:
    1:
      Messages:
        - 'You have failed 2FA for &bone&f time. If you will have failed 2FA &btwo&f more times, your IP address will be banned.'
      Commands: []
    3:
      Messages: []
      Commands:
        - 'banip %player% 30m Suspicious activity.'
  CommandsAfterVerification: []
  CommandsAfterUnlink: []
  CommandsAfterServerBoosting: []
  DelayedRolesCheck:
    Enabled: true
    Delay: 30
  DelayedNamesCheck:
    Enabled: true
    Delay: 30
  GuildVoiceRewards:
    Enabled: false
    Time: 600
    Reward: 'eco give %player% 100'
    BlacklistedChannels: []
  MessagesChannel:
    Enabled: false
    Id: -1
  ServerActivityLogging:
    Enabled: false
    ChannelId: -1
    JoinEmbedColor: '#8de113'
    QuitEmbedColor: '#f34520'
    DeathEmbedColor: '#f34520'
    ChatEmbedColor: '#e8d725'
  Console:
    Enabled: false
    ChannelId: -1
    BlacklistedCommands: []
  NotifyAboutMentions:
    Enabled: true
    Title:
      Enabled: true
      FadeIn: 3
      Stay: 50
      FadeOut: 3
      Title: '&bNew mention!'
      Subtitle: '&fCheck your &9Discord&f.'
    Message:
      Enabled: false
      Text: '&9DiscordUtils &7/&f You have been mentioned in &9Discord&f.'
    Sound:
      Enabled: true
      Type: 'ENTITY_EXPERIENCE_ORB_PICKUP'
      Volume: 1
      Pitch: 1
Database:
  Type: ''
  Host: 'localhost'
  Port: 3306
  Database: 'DiscordUtils'
  Username: 'root'
  Password: ''