# Плагин на пермишены, использующийся вами (оставьте пустым, если хотите отключить интеграцию)
# Доступные на данный момент плагины: LuckPerms, Vault (включает в себя поддержку множества плагинов, список: https://www.spigotmc.org/resources/vault.34315/)
PermissionsPlugin: 'LuckPerms'
# Проверка на наличие неустановленных обновлений плагина
CheckForUpdates: true
Discord:
  # Токен, необходимый для работы бота. Получить его можно здесь: https://discord.com/developers/applications
  BotToken: ''
  # Префикс, использующийся в командах бота
  BotPrefix: '!'
  # Сюда вводим роли по следующему формату: id_роли: 'название_группы'
  # Пример: 905508941230915684: 'admin'
  # Данные роли будут автоматически выдаваться, если у игрока есть соответствующая группа
  GroupRoles: {}
  # Сюда нужно вводить id ролей (списком)
  # Пример: AdminRoles: [905508941230915684, 123123123131231233]
  AdminRoles: []
  VerifiedRole:
    Id: -1 # id роли, выдающейся после верификации
    Enabled: true # true - выдавать, false - не выдавать
  2FAType: 'reaction' # Тип двухфакторной аутентификации. code - ввести код, reaction - нажать на реакцию в Discord'e
  2FASessions: true # Включить ли сессии (ненадобность прохождения 2FA, если айпи сохранился) для двухфакторной аутентификации