name: DiscordUtils
version: '2.3'
main: md.mirrerror.discordutils.Main
softdepend:
  - 'Vault'
  - 'LuckPerms'
  - 'PlaceholderAPI'
commands:
  discordutils:
    usage: ''
    description: ''
    aliases:
      - 'disutils'
      - 'du'
