name: DiscordUtils
version: '1.8'
main: md.mirrerror.discordutils.Main
softdepend:
  - 'Vault'
  - 'LuckPerms'
commands:
  discordutils:
    usage: ''
    description: ''
    aliases:
      - 'disutils'
      - 'du'
